### ISSUE TITLE
leere Zeichenketten NICHT

### ISSUE THREAD

**Issue by LarsFlieger** [JakWai01/application-security#5]
In Secure Coding 6: 

```java
public boolean checkValidPassword(String s) {
  // TODO: Implementieren Sie die Prüfung von Passwörtern so, dass
  //       1. null-Strings und leere Zeichenketten NICHT erlaubt sind
  //       2. ein Passwort mindestens 10 Zeichen haben muss.
  if (s == null || s.trim().isEmpty()) {
    return false;
  }
  if (s.length() < 10) {
    return false;
  }
  return true;
}
```

Was ist mit `1. null-Strings und leere Zeichenketten NICHT erlaubt sind` gemeint? 

Das nur eine leere Zeichenkette nicht erlaubt ist oder das generell leere Zeichenketten nicht erlaubt sind? (denke auf das leerzeichen in einem Passwort nicht üblich sind) 

In seiner aktuellen Implementierung würde nämlich das gehen: 
```
"s                                " ✓
``` 
Das aber nicht: 
``` 
"                                  " X
```

**Comment by JakWai01** [comment]
Damit ist gemeint, dass `""` und `null` nicht als Passwörter zugelassen sind.
